In [1]:
import os

In [4]:
os.getcwd()

'/Users/vunguyen/CS512_link_predictor'

In [5]:
os.chdir('/Users/vunguyen/CS512_link_predictor/data')

In [6]:
with open('id_pairs_hashed_sorted.txt') as f:
    content = f.read().splitlines()

In [7]:
unique_ids = set()

In [8]:
for i in xrange(len(content)):
    worker2manager = content[i].split('\t')
    unique_ids.add(worker2manager[0])
    unique_ids.add(worker2manager[1])

In [9]:
len(unique_ids)

469176

In [ ]:
60k*60k - 60k
(a, b) where a != b

In [68]:
tspace_interactions = {
                        'commented': {}, # actor => set of people
                        'liked': {}, 
                        'mentioned': {}
                      }
verbs = set()
# TODO: group similar actions
tspace_types_of_interaction = set(['commented', 'liked', 'mentioned'])

In [69]:
with open('anon_tSpace_sorted.txt') as f:
    content = f.read().splitlines()

In [70]:
for i in xrange(len(content)):
    record = content[i].split('|')
    
    if (len(record) >= 4 and record[1] in tspace_types_of_interaction):
        (time, action, page, actor, rest) = (record[0], record[1], record[2], record[3], record[4:])
    
        # must include (time, action, page, actor, receiver(s))
        if (actor not in tspace_interactions[action]):
            tspace_interactions[action][actor] = rest
        else:
            tspace_interactions[action][actor].extend(rest)

In [75]:
len(tspace_interactions['mentioned'].keys())

1671

In [84]:
tspace_interactions['mentioned']

{'0fa85790cf45': ['9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c73856896e7',
  '8e00a1a573e5',
  '0a6490de7078',
  '9c7385689

In [38]:
record

['2013-01-28T12:39:35.151-08:00',
 'liked',
 'd0bd7b93db07',
 'NoMATCH',
 'NoMATCH']

In [39]:
record[4:]

['NoMATCH']

In [45]:
test['bbb'] = record[4:]

In [47]:
test['bbb'].extend(['a','b'])

In [48]:
test['bbb']

['NoMATCH', 'a', 'b']

In [82]:
organization = {} # boss -> list of employees

with open('id_pairs_hashed_sorted.txt') as f:
    content = f.read().splitlines()

In [83]:
for i in xrange(len(content)):
    relation = content[i].split('\t')
    
    if (relation[1] not in organization.keys()):
        organization[relation[1]] = list()
    else:
        organization[relation[1]].append(relation[0])

In [85]:
organization

{'5b555ebbc01c': ['1ff9eda72032',
  '28948dfc596a',
  '54a51fcbb427',
  '57d84581feca',
  '590b8698ca1b',
  '87492c29e4ab',
  'c5f7abfdafd0',
  'fd200e78d47e'],
 '1058b1ad54d4': ['2394b8777e3f',
  '67ac5729dd80',
  '7c93d4dd84bf',
  '9f578aeae54c'],
 '3b2797649a07': ['19364cfcc1c2',
  '26e1731c07c7',
  '3cb360b5a273',
  '4364d39742cd',
  '5381138b52d7',
  '53c1f31e531c',
  '6b61b20bd048',
  '841c712bd607',
  '86dace72f892',
  'b0054d1f2ece',
  'c3a9656a666a',
  'd19b82a75b72',
  'e5cddbe09a24',
  'f5553298948b'],
 '7c27ca1fa289': [],
 '0635796dc7ad': [],
 '58e5fcd4ed1d': ['74719055a195',
  '779759415f85',
  '90acce90ef7d',
  'c875dd724653',
  'd78cf61ec0e4',
  'dd4c5ea5f37e',
  'e5f7b349830f',
  'f0f8f527ba49'],
 'f748b096375d': ['167d63ad20ab',
  '1e77880f05a8',
  '307a25c8a778',
  '33c75e9abaff',
  '48eba241ebac',
  '960d94af0a98',
  'c3dbd0073271',
  'c7091c494a51',
  'd17f4e41ccf2',
  'e4db73e49012',
  'ec555940973a'],
 'eafc1d477d29': ['3620a5f16954', '4724b9db3cd0'],
 '3a8b6d466e

In [95]:
# build matrices for tspace_interactions['mentioned'] and tspace_interactions['liked']

persons_involved_in_mentions = set()
persons_involved_in_likes = set()

for person in tspace_interactions['mentioned'].keys():
    persons_involved_in_mentions.add(person)
    for receiver in tspace_interactions['mentioned'][person]:
        persons_involved_in_mentions.add(receiver)

for person in tspace_interactions['liked'].keys():
    persons_involved_in_likes.add(person)
    for receiver in tspace_interactions['liked'][person]:
        persons_involved_in_likes.add(receiver)
    
#persons = persons_involved_in_mentions.union(person_involved_in_likes) 


In [96]:
len(persons_involved_in_likes)

11006

In [97]:
len(persons_involved_in_mentions)

5179

In [103]:
# sort the hash ids so 0 -> n maps to the sorted hash list
persons = list(sorted(persons_involved_in_mentions.union(persons_involved_in_likes)))

In [105]:
import numpy as np

In [199]:
LIKE = np.zeros((len(persons), len(persons)))
MENTION = np.zeros((len(persons), len(persons)))
# COMMENT

In [200]:
# create LIKE adjacency matrix
for person in tspace_interactions['liked'].keys():
    if person != 'NoMATCH':
        for receiver in tspace_interactions['liked'][person]:
            if receiver != 'NoMATCH':
                LIKE[persons.index(person), persons.index(receiver)] = 1
                #LIKE[persons.index(receiver), persons.index(person)] = 1
                
# create MENTION adjacency matrix
for person in tspace_interactions['mentioned'].keys():
    if person != 'NoMATCH':
        for receiver in tspace_interactions['mentioned'][person]:
            if receiver != 'NoMATCH':
                MENTION[persons.index(person), persons.index(receiver)] = 1
                #MENTION[persons.index(receiver), persons.index(person)] = 1                

In [ ]:
[LIKE, MENTION]
[MENTION, LIKE]
[MENTION, COMMENT]
[MENTION, COMMENT, LIKE]
[MENTION, COMMENT, MENTION, LIKE]

In [ ]:
tspace_interactions['liked']

In [ ]:
tspace_interactions['liked']['2b7ad7ce3b28']

In [150]:
tspace_interactions['mentioned']['1e87b267d849']

['NoMATCH',
 '2b7ad7ce3b28',
 'dffdb98d4c2c',
 'NoMATCH',
 '2b7ad7ce3b28',
 'dffdb98d4c2c',
 'NoMATCH',
 'NoMATCH',
 '95b1d5882a09',
 'NoMATCH',
 'NoMATCH',
 '95b1d5882a09']

In [ ]:
"""
def pathCount(mList):
    result = mList[0]
    for m in mList[1:]:
        result = np.dot(result, m)
    
    return result

def nPathCount(mList):
    mList_ = mList
    mList_.reverse()
    R = pathCount(mList)
    R_ = pathCount(mList_)
    result = np.zeros((len(R), len(R)))
    
    rowSums = np.sum(R, axis = 1)
    colSums = np.sum(R, axis = 0)
    
    for i in xrange(len(R)):
        for j in xrange(len(R)):
            if (rowSums[i] + colSums[j] != 0):
                result[i,j] = (R[i,j] + R_[j,i])/(rowSums[i] + colSums[j])
            
    return result

def randomWalk(mList):
    R = pathCount(mList)
    result = np.zeros((len(R), len(R)))
    rowSums = np.sum(R, axis = 1)
    
    for i in xrange(len(R)):
        for j in xrange(len(R)):
            if rowSums[i] != 0:
                result[i,j] = (R[i,j])/rowSums[i]
            
    return result

def sRandomWalk(mList):
    mList_ = mList
    mList_.reverse()
    R = randomWalk(mList)
    R_ = randomWalk(mList_)
    result = np.zeros((len(R), len(R)))
    
    for i in xrange(len(R)):
        for j in xrange(len(R)):
            result[i,j] = R[i,j] + R_[j,i]
            
    return result
"""

In [283]:
def generateMPFeatures(mList):
    # path count
    PC = mList[0]
    for m in mList[1:]:
        PC = np.dot(PC, m)

    # inverse path count
    mList_ = mList
    mList_.reverse()
    
    PC_ = mList_[0]
    for m in mList_[1:]:
        PC_ = np.dot(PC_, m)
    
    # normalized path count
    NPC = np.zeros((len(PC), len(PC)))
    
    rowSums = np.sum(PC, axis = 1)
    colSums = np.sum(PC, axis = 0)
    
    for i in xrange(len(PC)):
        for j in xrange(len(PC)):
            if (rowSums[i] + colSums[j] != 0):
                NPC[i,j] = (PC[i,j] + PC_[j,i])/(rowSums[i] + colSums[j])
    
    # random walk
    RW = np.zeros((len(PC), len(PC)))
    
    for i in xrange(len(R)):
        for j in xrange(len(R)):
            if rowSums[i] != 0:
                RW[i,j] = (PC[i,j])/rowSums[i]
    
    # symmetric random walk
    SRW = np.zeros((len(PC), len(PC)))
    
    for i in xrange(len(PC)):
        for j in xrange(len(PC)):
            SRW[i,j] = PC[i,j] + PC_[j,i]
    
    return (PC, NPC, RW, SRW)

In [302]:
PC_LM = pathCount([LIKE, MENTION])

In [319]:
# prep data

# forming feature set

In [ ]:
RW_LM = randomWalk([LIKE, MENTION])

In [ ]:
SRW_LM = sRandomWalk([LIKE, MENTION])

In [306]:
PC_ML = pathCount([MENTION, LIKE])

In [307]:
PC_ML

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [317]:
# PC_LM and PC_ML
result = np.zeros((len(PC_LM), len(PC_LM)))

rowSums = np.sum(PC_LM, axis = 1)
colSums = np.sum(PC_LM, axis = 0)

for i in xrange(len(PC_LM)):
    for j in xrange(len(PC_LM)):
        if (rowSums[i] + colSums[j] != 0):
            result[i,j] = (PC_LM[i,j] + PC_ML[j,i])/(rowSums[i] + colSums[j])

In [318]:
result

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.16666667,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.02521008,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [315]:
np.sum(PC_LM, axis=1) # row sum

array([  2.,   6.,   0., ...,   0.,  85.,   0.])

In [ ]:
"""
LIKE - MENTION
[0 1 0] [0 0 0] [0 0 1]
[0 0 0] [0 0 1]=[0 0 0]
[0 0 0] [0 0 0] [0 0 0]

MENTION - LIKE

LIKE - LIKE
[0 1 0] [0 1 0] [0 0 0]
[0 0 0] [0 0 0]=[0 0 0]
[0 0 0] [0 0 0] [0 0 0]

People - Meeting - People
M_PM <- symmetric
M_PM * M_PM^T
= M_PM * M_MP
[1 0 1] [1 0]
[0 1 1] [0 1]
        [1 1]
=
[2 1]
[1 2]

Commuting matrix
M_ii = visibility of i
M_ij for i != j: path instance i and j
"""

In [206]:
TEST = np.dot(LIKE, MENTION)

In [207]:
TEST[persons.index('2b7ad7ce3b28'), persons.index('dffdb98d4c2c')]

1.0